### ISSUE TITLE
Not able to view the image on the home screen

### ISSUE THREAD

**Issue by Rishika70** [Rishika70/Generative-AI-Course#1]
![image](https://github.com/Rishika70/Streamlit-for-Generative-AI/assets/75087210/53684833-e551-4589-9731-70e3022e51db)

I have attached the image file , still the issue is occurring , No text or image on the home screen

**Comment by Raykarr** [comment]
Did you check the path of the files in the code ?
Im sure its just a path issue

**Comment by Rishika70** [comment]
i have uploaded the image file in the same directory , still this issue
