### ISSUE TITLE
Not able to view the markdown attached , not for the lessons and also not for the projects 

### ISSUE THREAD

**Issue by Rishika70** [Rishika70/Generative-AI-Course#2]
![image](https://github.com/Rishika70/Streamlit-for-Generative-AI/assets/75087210/178587fc-2046-4ae3-8974-3eb3a25f730f)
this is the code i used - 
import streamlit as st
from utilities import load_css

st.set_page_config(page_title='Lesson 0 - Intro to streamlit')

load_css()

md = read_md("Lesson-0.md")
st.markdown(md, unsafe_allow_html=True

**Comment by Raykarr** [comment]
Can you please upload the markdowns as well

**Comment by Rishika70** [comment]
Oh yes , okay will attach rn

**Comment by Rishika70** [comment]
updated the code , pls check
