### ISSUE TITLE
There is a need to add images and links in the markdowns 

### ISSUE THREAD

**Issue by Rishika70** [Rishika70/Generative-AI-Course#3]
![image](https://github.com/Rishika70/Streamlit-for-Generative-AI/assets/75087210/309ca7da-28ca-48d7-b008-83361922037b)

**Comment by Raykarr** [comment]
I want to work on this repo , may i fork this and update the markdowns accordingly ?

**Comment by Rishika70** [comment]
yes , pls feel free to do so
