### ISSUE TITLE
Not able to redirect in streamlit to the next page even after clicking , PLs help

### ISSUE THREAD

**Issue by Rishika70** [Rishika70/Generative-AI-Course#5]
## Table of Contents
1. What is LangChain("What is LangChain")?
2. Installing LangChain ("Installing LangChain ")
3. Setting your OpenAI API key("Setting your OpenAI API key")
4. Using LangChain("Using LangChain")

**Comment by Srinivas-162003** [comment]
Are the name of the files the same ?
its a path issue
